import type { Locale, LocalizedText } from "@/lib/i18n";

/**
 * Раздел «Маркетинг»: цены, калькулятор и тексты страницы.
 *
 * Владелец, 04.10.2026: «Сделай на главной раздел с калькулятором по
 * маркетингу и целиком новую вкладку «Маркетинг»… Если клиент выбирает
 * разработка + маркетинг, то доработки багов и адаптации SEO будут
 * бесплатно от студии».
 *
 * Цены работ — те же, что в КП студии по маркетингу (03.10.2026): прайс
 * крупного агентства полного цикла Ташкента минус 10%. Комиссии с
 * рекламных бюджетов — без скидки, а на сам бюджет рекламные системы
 * начисляют НДС 12% (владелец, 04.10.2026). Меняются здесь — калькулятор,
 * таблица цен и ответы в «Вопросах» берут числа отсюда.
 */

/** НДС, который Яндекс, Telegram и другие рекламные системы берут с бюджета. */
export const AD_VAT = 0.12;
/** Комиссия студии с рекламного бюджета. */
export const AD_COMMISSION = 0.1;
/** Скидка на работу при оплате трёх месяцев вперёд. */
export const PREPAY_DISCOUNT = 0.05;
/** Бюджет по умолчанию в калькуляторе — около $500, «на старт». */
export const DEFAULT_AD_BUDGET = 6_500_000;
export const AD_BUDGET_STEP = 500_000;
export const AD_BUDGET_MAX = 130_000_000;

export type MarketingChannel = {
  id: string;
  title: LocalizedText;
  note: LocalizedText;
  /** Работа в месяц, сум. */
  monthly: number;
  /** Первый месяц: стратегия, стиль, медиаплан, кабинеты. */
  first: number;
  /** Канал с рекламным бюджетом — на него НДС системы и наша комиссия. */
  ads: boolean;
  /** Цена «от»: объём задач согласуется. */
  from?: boolean;
  /** Взаимоисключающие варианты одного канала. */
  group?: "context";
};

const L = (ru: string, en: string, uz: string, zh: string, uk: string, pl: string): LocalizedText => ({ ru, en, uz, zh, uk, pl });

export const channels: MarketingChannel[] = [
  {
    id: "smm",
    title: L("SMM-продвижение", "SMM", "SMM", "社媒运营", "SMM-просування", "Prowadzenie social mediów"),
    note: L(
      "Instagram, Facebook, Telegram: 4 съёмки, 8 рилс, 4 поста, 30 сторис в месяц, тексты на русском и узбекском",
      "Instagram, Facebook, Telegram: 4 shoots, 8 reels, 4 posts and 30 stories a month, texts in Russian and Uzbek",
      "Instagram, Facebook, Telegram: oyiga 4 ta suratga olish, 8 ta rils, 4 ta post, 30 ta storis, rus va o‘zbek tilida matnlar",
      "Instagram、Facebook、Telegram：每月 4 次拍摄、8 条短视频、4 篇帖子、30 条快拍，俄语与乌兹别克语文案",
      "Instagram, Facebook, Telegram: 4 зйомки, 8 рілс, 4 пости і 30 сторіс на місяць, тексти російською та узбецькою",
      "Instagram, Facebook, Telegram: 4 sesje, 8 rolek, 4 posty i 30 relacji miesięcznie, teksty po rosyjsku i uzbecku",
    ),
    monthly: 23_256_000,
    first: 35_856_000,
    ads: false,
  },
  {
    id: "target",
    title: L("Таргет в Instagram и Facebook", "Instagram and Facebook ads", "Instagram va Facebook’da target", "Instagram 与 Facebook 定向广告", "Таргет в Instagram і Facebook", "Reklama w Instagramie i na Facebooku"),
    note: L(
      "Медиаплан, 4 креатива в месяц, пиксель на сайте, ретаргетинг, заявки сразу в CRM",
      "Media plan, 4 creatives a month, pixel on the site, retargeting, leads straight into the CRM",
      "Mediareja, oyiga 4 ta kreativ, saytda piksel, retargeting, arizalar to‘g‘ridan-to‘g‘ri CRM’ga",
      "媒体计划、每月 4 个创意、网站像素、再营销，线索直接进入 CRM",
      "Медіаплан, 4 креативи на місяць, піксель на сайті, ретаргетинг, заявки одразу в CRM",
      "Media plan, 4 kreacje miesięcznie, piksel na stronie, retargeting, zgłoszenia od razu w CRM",
    ),
    monthly: 7_200_000,
    first: 9_000_000,
    ads: true,
  },
  {
    id: "context-google",
    title: L("Контекст в Google", "Google Ads", "Google’da kontekst reklama", "Google 搜索广告", "Контекст у Google", "Google Ads"),
    note: L(
      "Поиск, ремаркетинг, Google Merchant, профиль компании, цели в аналитике",
      "Search, remarketing, Google Merchant, business profile, analytics goals",
      "Qidiruv, remarketing, Google Merchant, kompaniya profili, analitikada maqsadlar",
      "搜索广告、再营销、Google Merchant、商家资料、分析目标",
      "Пошук, ремаркетинг, Google Merchant, профіль компанії, цілі в аналітиці",
      "Wyszukiwarka, remarketing, Google Merchant, profil firmy, cele w analityce",
    ),
    monthly: 6_615_000,
    first: 9_135_000,
    ads: true,
    group: "context",
  },
  {
    id: "context-both",
    title: L("Контекст в Google и Яндексе", "Google and Yandex ads", "Google va Yandex’da kontekst reklama", "Google 与 Yandex 搜索广告", "Контекст у Google і Яндексі", "Google Ads i Yandex Direct"),
    note: L(
      "Всё то же плюс Яндекс Директ и РСЯ, единая отчётность",
      "All of the above plus Yandex Direct and its ad network, one report",
      "Yuqoridagilarning barchasi va Yandex Direct, yagona hisobot",
      "以上全部，外加 Yandex Direct 及其广告网络，统一报告",
      "Усе те саме плюс Яндекс Директ і РСЯ, єдина звітність",
      "Wszystko powyżej plus Yandex Direct i jego sieć reklamowa, jeden raport",
    ),
    monthly: 9_315_000,
    first: 12_195_000,
    ads: true,
    group: "context",
  },
  {
    id: "telegram",
    title: L("Реклама в Telegram", "Telegram Ads", "Telegram’da reklama", "Telegram 广告", "Реклама в Telegram", "Reklama w Telegramie"),
    note: L(
      "Подбор каналов, Telegram Ads, отчёт каждую неделю",
      "Channel selection, Telegram Ads, weekly report",
      "Kanallarni tanlash, Telegram Ads, har hafta hisobot",
      "频道筛选、Telegram Ads、每周报告",
      "Добір каналів, Telegram Ads, звіт щотижня",
      "Dobór kanałów, Telegram Ads, raport co tydzień",
    ),
    monthly: 2_970_000,
    first: 4_410_000,
    ads: true,
  },
  {
    id: "seo",
    title: L("SEO-продвижение", "SEO", "SEO", "SEO 优化", "SEO-просування", "Pozycjonowanie SEO"),
    note: L(
      "Аудит, техническая оптимизация, запросы, тексты, позиции в Google и Яндексе. От 3 месяцев",
      "Audit, technical optimisation, keywords, copy, rankings in Google and Yandex. From 3 months",
      "Audit, texnik optimallashtirish, so‘rovlar, matnlar, Google va Yandex’dagi o‘rinlar. 3 oydan",
      "审计、技术优化、关键词、文案、Google 与 Yandex 排名。至少 3 个月",
      "Аудит, технічна оптимізація, запити, тексти, позиції в Google і Яндексі. Від 3 місяців",
      "Audyt, optymalizacja techniczna, frazy, teksty, pozycje w Google i Yandex. Od 3 miesięcy",
    ),
    monthly: 4_500_000,
    first: 4_500_000,
    ads: false,
  },
  {
    id: "support",
    title: L("Маркетинг-сопровождение", "Marketing management", "Marketing kuzatuvi", "营销统筹", "Маркетинговий супровід", "Opieka marketingowa"),
    note: L(
      "Все каналы как один план: планёрки каждую неделю, единый отчёт с окупаемостью рекламы",
      "All channels as one plan: weekly meetings, one report with return on ad spend",
      "Barcha kanallar yagona reja sifatida: har haftalik yig‘ilishlar, reklama qoplanishi bilan yagona hisobot",
      "所有渠道统一规划：每周例会，含广告回报率的统一报告",
      "Усі канали як один план: планірки щотижня, єдиний звіт з окупністю реклами",
      "Wszystkie kanały jako jeden plan: cotygodniowe spotkania, jeden raport ze zwrotem z reklamy",
    ),
    monthly: 9_000_000,
    first: 9_000_000,
    ads: false,
  },
  {
    id: "design",
    title: L("Дизайн-поддержка", "Design support", "Dizayn yordami", "设计支持", "Дизайн-підтримка", "Wsparcie graficzne"),
    note: L(
      "Полиграфия, POS-материалы, наружная реклама, презентации, баннеры сайта",
      "Print, POS materials, outdoor ads, presentations, website banners",
      "Poligrafiya, POS-materiallar, tashqi reklama, taqdimotlar, sayt bannerlari",
      "印刷品、POS 物料、户外广告、演示文稿、网站横幅",
      "Поліграфія, POS-матеріали, зовнішня реклама, презентації, банери сайту",
      "Druk, materiały POS, reklama zewnętrzna, prezentacje, banery na stronę",
    ),
    monthly: 6_300_000,
    first: 6_300_000,
    ads: false,
    from: true,
  },
];

export type MarketingProject = {
  id: string;
  title: LocalizedText;
  note: LocalizedText;
  price: number;
  from: boolean;
  term: LocalizedText;
  perHour?: boolean;
};

const DAYS10 = L("от 10 дней", "from 10 days", "10 kundan", "10 天起", "від 10 днів", "od 10 dni");
const DAYS7 = L("от 7 дней", "from 7 days", "7 kundan", "7 天起", "від 7 днів", "od 7 dni");

export const projects: MarketingProject[] = [
  {
    id: "reels",
    title: L("Видео-рилс", "Reels", "Video rils", "短视频", "Відео-рілс", "Rolki wideo"),
    note: L("3 ролика: сценарии, съёмка, монтаж, обложки", "3 videos: scripts, shoot, edit, covers", "3 ta rolik: ssenariy, suratga olish, montaj, muqovalar", "3 条视频：脚本、拍摄、剪辑、封面", "3 ролики: сценарії, зйомка, монтаж, обкладинки", "3 filmy: scenariusze, zdjęcia, montaż, okładki"),
    price: 8_460_000, from: true, term: DAYS10,
  },
  {
    id: "production",
    title: L("Продакшн-видео", "Video production", "Video prodakshn", "视频制作", "Продакшн-відео", "Produkcja wideo"),
    note: L("Камера, свет, звук, режиссура, монтаж", "Camera, light, sound, directing, editing", "Kamera, yorug‘lik, ovoz, rejissura, montaj", "摄影、灯光、收音、导演、剪辑", "Камера, світло, звук, режисура, монтаж", "Kamera, światło, dźwięk, reżyseria, montaż"),
    price: 9_045_000, from: true, term: DAYS7,
  },
  {
    id: "motion",
    title: L("Моушн-дизайн", "Motion design", "Moushn-dizayn", "动态设计", "Моушн-дизайн", "Motion design"),
    note: L("2D, 3D, AI-анимация, озвучка", "2D, 3D and AI animation, voice-over", "2D, 3D, AI animatsiya, ovoz berish", "2D、3D、AI 动画及配音", "2D, 3D, AI-анімація, озвучення", "Animacja 2D, 3D i AI, lektor"),
    price: 4_185_000, from: true, term: DAYS7,
  },
  {
    id: "photo",
    title: L("Фотосессия", "Photo shoot", "Fotosessiya", "摄影", "Фотосесія", "Sesja zdjęciowa"),
    note: L("Предметная, фуд, портреты, репортаж", "Product, food, portraits, reportage", "Predmetli, taomlar, portretlar, reportaj", "产品、美食、人像、活动纪实", "Предметна, фуд, портрети, репортаж", "Produktowa, kulinarna, portrety, reportaż"),
    price: 4_365_000, from: true, term: DAYS7,
  },
  {
    id: "branding",
    title: L("Брендинг", "Branding", "Brending", "品牌设计", "Брендинг", "Branding"),
    note: L("Нейминг, логотип, фирменный стиль, брендбук", "Naming, logo, identity, brand book", "Neyming, logotip, firma uslubi, brendbuk", "命名、标志、视觉识别、品牌手册", "Неймінг, логотип, фірмовий стиль, брендбук", "Nazwa, logo, identyfikacja, brandbook"),
    price: 39_600_000, from: false, term: L("2 месяца", "2 months", "2 oy", "2 个月", "2 місяці", "2 miesiące"),
  },
  {
    id: "strategy",
    title: L("Digital-стратегия", "Digital strategy", "Digital strategiya", "数字营销策略", "Digital-стратегія", "Strategia digital"),
    note: L("Аудит всех каналов, конкуренты, KPI, медиаплан", "Audit of all channels, competitors, KPIs, media plan", "Barcha kanallar auditi, raqobatchilar, KPI, mediareja", "全渠道审计、竞品、KPI、媒体计划", "Аудит усіх каналів, конкуренти, KPI, медіаплан", "Audyt kanałów, konkurencja, KPI, media plan"),
    price: 54_000_000, from: true, term: L("1,5 месяца", "6 weeks", "1,5 oy", "6 周", "1,5 місяця", "6 tygodni"),
  },
  {
    id: "research",
    title: L("Исследование рынка", "Market research", "Bozor tadqiqoti", "市场调研", "Дослідження ринку", "Badanie rynku"),
    note: L("10 интервью, опрос 100 человек, поисковые запросы", "10 interviews, survey of 100 people, search queries", "10 ta intervyu, 100 kishilik so‘rovnoma, qidiruv so‘rovlari", "10 次访谈、100 人问卷、搜索词分析", "10 інтерв’ю, опитування 100 людей, пошукові запити", "10 wywiadów, ankieta 100 osób, frazy wyszukiwania"),
    price: 8_550_000, from: false, term: L("20 дней", "20 days", "20 kun", "20 天", "20 днів", "20 dni"),
  },
  {
    id: "sales",
    title: L("Отдел продаж под ключ", "Sales department setup", "Sotuv bo‘limi kalit topshirish", "销售部门搭建", "Відділ продажів під ключ", "Dział sprzedaży pod klucz"),
    note: L("CRM, воронка, скрипты, KPI, обучение, месяц сопровождения", "CRM, pipeline, scripts, KPIs, training, a month of support", "CRM, voronka, skriptlar, KPI, o‘qitish, bir oylik kuzatuv", "CRM、销售漏斗、话术、KPI、培训及一个月跟进", "CRM, воронка, скрипти, KPI, навчання, місяць супроводу", "CRM, lejek, skrypty, KPI, szkolenia, miesiąc wsparcia"),
    price: 19_800_000, from: false, term: L("1,5 месяца", "6 weeks", "1,5 oy", "6 周", "1,5 місяця", "6 tygodni"),
  },
  {
    id: "consulting",
    title: L("Маркетинг-консалтинг", "Marketing consulting", "Marketing konsalting", "营销咨询", "Маркетинг-консалтинг", "Konsulting marketingowy"),
    note: L("Разбор задачи с экспертом и план действий", "A session with an expert and an action plan", "Ekspert bilan vazifani tahlil qilish va harakat rejasi", "与专家逐项分析并给出行动计划", "Розбір задачі з експертом і план дій", "Sesja z ekspertem i plan działań"),
    price: 1_350_000, from: true, term: L("час", "hour", "soat", "小时", "година", "godzina"), perHour: true,
  },
];

const ru = {
  seoTitle: "Маркетинг и продвижение бизнеса в Ташкенте: SMM, таргет, контекст — DevUz Studio",
  seoDescription:
    "SMM, таргет в Instagram, контекстная реклама Google и Яндекс, Telegram Ads и SEO от студии, которая делает ваш сайт. Калькулятор стоимости онлайн. Сайт и маркетинг у нас — исправления и SEO-доработки бесплатно.",
  kicker: "Маркетинг",
  title: "Маркетинг, который приводит заявки, а не только охваты",
  lead: "SMM, таргет, контекст в Google и Яндексе, Telegram Ads и SEO — одной командой. Все каналы ведут на сайт, который мы знаем до последней кнопки, а каждая заявка попадает в CRM с пометкой канала.",
  ctaCalc: "Рассчитать маркетинг",
  ctaDiscuss: "Обсудить продвижение",
  utp: {
    badge: "Сайт + маркетинг",
    title: "Делаем сайт и продвигаем его — исправления и SEO-доработки бесплатно",
    text: "Пока ваш сайт на продвижении у DevUz, исправляем ошибки сайта и делаем SEO-доработки без доплаты: скорость загрузки, метатеги и разметка, заголовки и тексты под поисковые запросы, технические правки после обновлений Google и Яндекса.",
    fine: "Условие — сайт сделан у нас и действует договор на маркетинг от 3 месяцев. Новые разделы и функции считаем отдельно.",
  },
  whyTitle: "Почему продвигаться у тех, кто делал сайт",
  why: [
    { title: "SEO — только один канал, и самый медленный", text: "Первые заявки из поиска приходят через 3–6 месяцев. А решение о покупке часто принимают раньше — в Instagram и Telegram." },
    { title: "Все каналы ведут на сайт, который мы знаем изнутри", text: "Пиксели, теги, цели и события на кнопках ставим сами, в тот же день, без ТЗ стороннему разработчику." },
    { title: "Каждая заявка — в одну CRM и Telegram", text: "Из рекламы, Instagram, Telegram Ads и поиска — в одно место с пометкой канала. Видно, что приносит продажи." },
    { title: "Никакого «это не к нам»", text: "Реклама ведёт на страницу, которая плохо продаёт, — правим страницу сами. Не нужно выяснять, кто виноват." },
    { title: "Один договор, один менеджер, один отчёт", text: "Раз в месяц — заявки, стоимость заявки и продажи по каждому каналу на одной странице." },
    { title: "Дешевле крупных агентств", text: "Работа на 10% дешевле прайса крупных агентств полного цикла Ташкента при том же составе." },
  ],
  calc: {
    kicker: "Калькулятор",
    title: "Калькулятор маркетинга",
    lead: "Отметьте каналы и бюджет на рекламу — посчитаем первый месяц и ежемесячную стоимость.",
    channels: "Каналы",
    context: "Контекстная реклама",
    contextNone: "Без контекста",
    contextGoogle: "Google",
    contextBoth: "Google и Яндекс",
    budget: "Рекламный бюджет в месяц",
    budgetHint: "Платится напрямую в рекламные системы. На старт — от $500 на канал.",
    siteToo: "Сайт тоже делаем мы",
    siteTooHint: "Исправления и SEO-доработки сайта — бесплатно",
    firstMonth: "Первый месяц",
    monthly: "Работа в месяц",
    adBudget: "Рекламный бюджет",
    vat: "НДС 12% рекламных систем",
    commission: "Комиссия 10% от бюджета",
    total: "Всего в месяц с рекламой",
    prepay: "При оплате 3 месяцев вперёд — минус 5% на работу",
    discuss: "Обсудить в чате",
    sent: "Расчёт в чате — ответим там",
    empty: "Выберите хотя бы один канал",
    prefill: "Хочу маркетинг: {channels}. Рекламный бюджет — {budget} в месяц. По калькулятору: первый месяц {first}, дальше {monthly} в месяц за работу.",
    prefillSite: " Сайт тоже делаете вы.",
  },
  servicesTitle: "Услуги и цены",
  servicesLead: "Первый месяц дороже: в него входят стратегия, фирменный стиль страниц, медиаплан и настройка кабинетов.",
  monthlyCol: "В месяц",
  firstCol: "Первый месяц",
  from: "от",
  plusCommission: "+ 10% от рекламного бюджета",
  projectsTitle: "Разовые проекты",
  perHour: "/ час",
  budgetBased: [
    "Инфлюенс-маркетинг — 20% от бюджета кампании, бюджет от $1 000.",
    "Медийная реклама (programmatic) — 15% от рекламного бюджета, бюджет от $1 000.",
    "PR-продвижение — от 7 200 000 сум в месяц плюс 20% от бюджета размещений.",
  ],
  vatNote: "Рекламный бюджет оплачивается отдельно: Яндекс, Telegram и другие рекламные системы начисляют на него НДС 12%. Цены студии — в сумах, без НДС.",
  processTitle: "Как начинаем",
  process: [
    { when: "Неделя 1", what: "Бриф, аудит сайта, соцсетей и рекламных кабинетов, доступы" },
    { when: "Неделя 2", what: "Стратегия, медиаплан и контент-план — показываем и согласуем" },
    { when: "Запуск", what: "Съёмки, первые публикации, рекламные кампании, заявки в CRM" },
    { when: "Каждую неделю", what: "Оптимизация рекламы, отчёт по заявкам и их стоимости" },
    { when: "Раз в месяц", what: "Итоги по каналам и план на следующий месяц" },
  ],
  faqTitle: "Вопросы о продвижении",
  faq: [
    { q: "Сколько стоит продвижение в Instagram в Ташкенте?", a: "SMM под ключ — {smm} в месяц, таргет в Instagram и Facebook — {target} в месяц плюс рекламный бюджет. Точную сумму под ваши каналы покажет калькулятор на этой странице." },
    { q: "Почему нельзя ограничиться SEO?", a: "SEO даёт первые заявки через 3–6 месяцев и только из поиска. Таргет и реклама в Telegram приносят обращения с первой недели, а SMM прогревает тех, кто пока выбирает. Вместе каналы работают дешевле: реклама догоняет посетителей сайта, а поиск подхватывает тех, кто запомнил бренд." },
    { q: "Что входит в бесплатные доработки сайта?", a: "Если сайт сделан у нас и действует договор на маркетинг от 3 месяцев — исправление ошибок, скорость загрузки, метатеги и разметка, заголовки и тексты под поисковые запросы, технические правки для Google и Яндекса. Новые разделы и функции — по отдельной смете." },
    { q: "Кто платит НДС с рекламы?", a: "Рекламный бюджет вы оплачиваете напрямую в рекламные системы — Яндекс, Telegram и другие начисляют на него НДС 12%. Наша комиссия — 10% от бюджета, работа студии — без НДС." },
    { q: "Можно ли подключить один канал?", a: "Да. Чаще всего начинают с таргета в Instagram или рекламы в Telegram — они дают заявки с первой недели. Остальные каналы подключаются, когда понятно, какие предложения продают лучше." },
    { q: "Какой минимальный срок договора?", a: "Три месяца: за меньший срок реклама не успевает обучиться, а SEO — показать результат. Дальше — помесячно." },
  ],
  articlesTitle: "Статьи о маркетинге",
  articlesLead: "Короткие разборы известных кейсов и частых ошибок — и что из этого применить в Узбекистане. Новые статьи выходят каждый день.",
  readMore: "Читать",
  sourceLabel: "Источник фактов",
  tipsTitle: "Что сделать у себя",
  articleCtaTitle: "Нужен маркетинг, который приводит заявки?",
  articleCtaText: "Посчитайте каналы в калькуляторе или напишите нам — ответим в течение рабочего дня.",
  articleCtaButton: "Открыть калькулятор",
  allArticles: "Все статьи о маркетинге",
  homeKicker: "Маркетинг",
  homeTitle: "Посчитайте продвижение сайта",
  homeLead: "SMM, таргет, контекст, Telegram Ads и SEO — одной командой. Если сайт делаем мы, исправления и SEO-доработки — бесплатно.",
  homeMore: "Всё о маркетинге",
  home: "Главная",
};

export type MarketingCopy = typeof ru;

const en: MarketingCopy = {
  seoTitle: "Digital marketing in Tashkent: SMM, paid social, Google and Yandex ads — DevUz Studio",
  seoDescription:
    "SMM, Instagram ads, Google and Yandex search ads, Telegram Ads and SEO from the studio that builds your website. Online cost calculator. Website plus marketing with us — fixes and SEO improvements free of charge.",
  kicker: "Marketing",
  title: "Marketing that brings enquiries, not just reach",
  lead: "SMM, paid social, Google and Yandex ads, Telegram Ads and SEO from one team. Every channel leads to a website we know down to the last button, and every enquiry lands in the CRM tagged with its channel.",
  ctaCalc: "Estimate marketing",
  ctaDiscuss: "Discuss promotion",
  utp: {
    badge: "Website + marketing",
    title: "We build your website and promote it — fixes and SEO improvements are free",
    text: "While your website is being promoted by DevUz, we fix site bugs and make SEO improvements at no extra cost: loading speed, meta tags and structured data, headings and copy for search queries, technical changes after Google and Yandex updates.",
    fine: "Applies when the website was built by us and a marketing contract of at least 3 months is active. New sections and features are quoted separately.",
  },
  whyTitle: "Why promote with the team that built the site",
  why: [
    { title: "SEO is one channel, and the slowest", text: "The first search enquiries arrive after 3–6 months, while buying decisions are often made earlier — on Instagram and Telegram." },
    { title: "Every channel leads to a site we know inside out", text: "We set up pixels, tags, goals and button events ourselves the same day — no brief for an outside developer." },
    { title: "Every enquiry goes into one CRM and Telegram", text: "From ads, Instagram, Telegram Ads and search — one place, tagged by channel. You see what actually sells." },
    { title: "No “not our problem”", text: "If an ad leads to a page that sells poorly, we fix the page ourselves. Nobody has to work out whose fault it is." },
    { title: "One contract, one manager, one report", text: "Once a month: enquiries, cost per enquiry and sales for every channel on a single page." },
    { title: "Cheaper than large agencies", text: "The work costs 10% less than the price list of Tashkent’s large full-service agencies, with the same scope." },
  ],
  calc: {
    kicker: "Calculator",
    title: "Marketing calculator",
    lead: "Pick the channels and the ad budget — we will estimate the first month and the monthly cost.",
    channels: "Channels",
    context: "Search ads",
    contextNone: "No search ads",
    contextGoogle: "Google",
    contextBoth: "Google and Yandex",
    budget: "Monthly ad budget",
    budgetHint: "Paid directly to the ad platforms. To start, from $500 per channel.",
    siteToo: "We are building the website too",
    siteTooHint: "Website fixes and SEO improvements are free",
    firstMonth: "First month",
    monthly: "Work per month",
    adBudget: "Ad budget",
    vat: "12% VAT charged by ad platforms",
    commission: "10% commission on the budget",
    total: "Total per month incl. ads",
    prepay: "Pay 3 months upfront — 5% off the work",
    discuss: "Discuss in chat",
    sent: "The estimate is in the chat — we will reply there",
    empty: "Pick at least one channel",
    prefill: "I want marketing: {channels}. Ad budget — {budget} a month. Calculator estimate: first month {first}, then {monthly} a month for the work.",
    prefillSite: " You are building the website too.",
  },
  servicesTitle: "Services and prices",
  servicesLead: "The first month costs more: it includes the strategy, page style, media plan and account setup.",
  monthlyCol: "Per month",
  firstCol: "First month",
  from: "from",
  plusCommission: "+ 10% of the ad budget",
  projectsTitle: "One-off projects",
  perHour: "/ hour",
  budgetBased: [
    "Influencer marketing — 20% of the campaign budget, budget from $1,000.",
    "Programmatic display ads — 15% of the ad budget, budget from $1,000.",
    "PR — from 7,200,000 UZS a month plus 20% of the placement budget.",
  ],
  vatNote: "The ad budget is paid separately: Yandex, Telegram and other ad platforms charge 12% VAT on it. Studio prices are in UZS, without VAT.",
  processTitle: "How we start",
  process: [
    { when: "Week 1", what: "Brief, audit of the website, social media and ad accounts, access" },
    { when: "Week 2", what: "Strategy, media plan and content plan — we present and agree them" },
    { when: "Launch", what: "Shoots, first posts, ad campaigns, enquiries into the CRM" },
    { when: "Every week", what: "Ad optimisation, report on enquiries and their cost" },
    { when: "Every month", what: "Results by channel and the plan for next month" },
  ],
  faqTitle: "Questions about promotion",
  faq: [
    { q: "How much does Instagram promotion cost in Tashkent?", a: "Full-service SMM is {smm} a month, Instagram and Facebook ads are {target} a month plus the ad budget. The calculator on this page shows the exact total for your channels." },
    { q: "Why not rely on SEO alone?", a: "SEO brings its first enquiries after 3–6 months and only from search. Paid social and Telegram ads bring enquiries from the first week, and SMM warms up people who are still choosing. Together the channels cost less: ads follow up site visitors, and search picks up those who remember the brand." },
    { q: "What do the free website improvements cover?", a: "If we built the website and a marketing contract of at least 3 months is active: bug fixes, loading speed, meta tags and structured data, headings and copy for search queries, technical changes for Google and Yandex. New sections and features are quoted separately." },
    { q: "Who pays VAT on advertising?", a: "You pay the ad budget directly to the ad platforms — Yandex, Telegram and others charge 12% VAT on it. Our commission is 10% of the budget; the studio’s work has no VAT." },
    { q: "Can I start with one channel?", a: "Yes. Most clients start with Instagram ads or Telegram ads — they bring enquiries from the first week. Other channels are added once it is clear which offers sell best." },
    { q: "What is the minimum contract term?", a: "Three months: in less time ads do not finish learning and SEO cannot show results. After that, month to month." },
  ],
  articlesTitle: "Marketing articles",
  articlesLead: "Short notes on well-known cases and common mistakes, and what to apply in Uzbekistan.",
  readMore: "Read",
  sourceLabel: "Source of facts",
  tipsTitle: "What to do in your business",
  articleCtaTitle: "Need marketing that brings enquiries?",
  articleCtaText: "Estimate the channels in the calculator or write to us — we reply within a working day.",
  articleCtaButton: "Open the calculator",
  allArticles: "All marketing articles",
  homeKicker: "Marketing",
  homeTitle: "Estimate your website promotion",
  homeLead: "SMM, paid social, search ads, Telegram Ads and SEO from one team. If we build your website, fixes and SEO improvements are free.",
  homeMore: "All about marketing",
  home: "Home",
};

const uz: MarketingCopy = {
  seoTitle: "Toshkentda biznes marketingi: SMM, target, kontekst reklama — DevUz Studio",
  seoDescription:
    "Saytingizni yaratadigan studiyadan SMM, Instagram’da target, Google va Yandex’da kontekst reklama, Telegram Ads va SEO. Onlayn narx kalkulyatori. Sayt va marketing bizda — xatolarni tuzatish va SEO yaxshilashlar bepul.",
  kicker: "Marketing",
  title: "Faqat qamrov emas, arizalar olib keladigan marketing",
  lead: "SMM, target, Google va Yandex’da kontekst reklama, Telegram Ads va SEO — bitta jamoa. Barcha kanallar biz oxirgi tugmasigacha biladigan saytga olib boradi, har bir ariza esa kanal belgisi bilan CRM’ga tushadi.",
  ctaCalc: "Marketingni hisoblash",
  ctaDiscuss: "Reklamani muhokama qilish",
  utp: {
    badge: "Sayt + marketing",
    title: "Saytni yaratamiz va uni reklama qilamiz — tuzatishlar va SEO yaxshilashlar bepul",
    text: "Saytingiz DevUz’da reklama qilinayotgan paytda sayt xatolarini tuzatamiz va SEO yaxshilashlarni qo‘shimcha to‘lovsiz qilamiz: yuklanish tezligi, metateglar va belgilash, qidiruv so‘rovlari uchun sarlavhalar va matnlar, Google va Yandex yangilanishlaridan keyingi texnik tuzatishlar.",
    fine: "Shart — sayt bizda yaratilgan va kamida 3 oylik marketing shartnomasi amal qiladi. Yangi bo‘limlar va funksiyalar alohida hisoblanadi.",
  },
  whyTitle: "Nega saytni yaratganlar bilan reklama qilish kerak",
  why: [
    { title: "SEO — faqat bitta kanal va eng sekini", text: "Qidiruvdan birinchi arizalar 3–6 oydan keyin keladi. Xarid haqidagi qaror esa ko‘pincha avvalroq — Instagram va Telegram’da qabul qilinadi." },
    { title: "Barcha kanallar biz ichidan biladigan saytga olib boradi", text: "Piksellar, teglar, maqsadlar va tugmalardagi hodisalarni o‘sha kuniyoq o‘zimiz o‘rnatamiz — tashqi dasturchiga texnik topshiriqsiz." },
    { title: "Har bir ariza — bitta CRM va Telegram’ga", text: "Reklama, Instagram, Telegram Ads va qidiruvdan — kanal belgisi bilan bitta joyga. Nima sotayotgani ko‘rinib turadi." },
    { title: "«Bu bizga tegishli emas» yo‘q", text: "Reklama yomon sotadigan sahifaga olib borsa — sahifani o‘zimiz tuzatamiz. Kim aybdorligini aniqlash shart emas." },
    { title: "Bitta shartnoma, bitta menejer, bitta hisobot", text: "Oyiga bir marta — har bir kanal bo‘yicha arizalar, ariza narxi va sotuvlar bitta sahifada." },
    { title: "Yirik agentliklardan arzonroq", text: "Ish Toshkentdagi to‘liq siklli yirik agentliklar narxidan 10% arzon, tarkibi o‘sha." },
  ],
  calc: {
    kicker: "Kalkulyator",
    title: "Marketing kalkulyatori",
    lead: "Kanallar va reklama byudjetini belgilang — birinchi oy va oylik narxni hisoblaymiz.",
    channels: "Kanallar",
    context: "Kontekst reklama",
    contextNone: "Kontekstsiz",
    contextGoogle: "Google",
    contextBoth: "Google va Yandex",
    budget: "Oylik reklama byudjeti",
    budgetHint: "To‘g‘ridan-to‘g‘ri reklama tizimlariga to‘lanadi. Boshlash uchun — har bir kanalga $500 dan.",
    siteToo: "Saytni ham biz qilamiz",
    siteTooHint: "Sayt tuzatishlari va SEO yaxshilashlar — bepul",
    firstMonth: "Birinchi oy",
    monthly: "Oylik ish",
    adBudget: "Reklama byudjeti",
    vat: "Reklama tizimlarining 12% QQS",
    commission: "Byudjetdan 10% komissiya",
    total: "Reklama bilan oyiga jami",
    prepay: "3 oy oldindan to‘lansa — ishga 5% chegirma",
    discuss: "Chatda muhokama qilish",
    sent: "Hisob chatda — o‘sha yerda javob beramiz",
    empty: "Kamida bitta kanalni tanlang",
    prefill: "Marketing kerak: {channels}. Reklama byudjeti — oyiga {budget}. Kalkulyator bo‘yicha: birinchi oy {first}, keyin ish uchun oyiga {monthly}.",
    prefillSite: " Saytni ham siz qilasiz.",
  },
  servicesTitle: "Xizmatlar va narxlar",
  servicesLead: "Birinchi oy qimmatroq: unga strategiya, sahifalar uslubi, mediareja va kabinetlarni sozlash kiradi.",
  monthlyCol: "Oyiga",
  firstCol: "Birinchi oy",
  from: "dan",
  plusCommission: "+ reklama byudjetidan 10%",
  projectsTitle: "Bir martalik loyihalar",
  perHour: "/ soat",
  budgetBased: [
    "Influens-marketing — kampaniya byudjetidan 20%, byudjet $1 000 dan.",
    "Mediyali reklama (programmatic) — reklama byudjetidan 15%, byudjet $1 000 dan.",
    "PR — oyiga 7 200 000 so‘mdan va joylashtirish byudjetidan 20%.",
  ],
  vatNote: "Reklama byudjeti alohida to‘lanadi: Yandex, Telegram va boshqa reklama tizimlari unga 12% QQS qo‘shadi. Studiya narxlari — so‘mda, QQSsiz.",
  processTitle: "Qanday boshlaymiz",
  process: [
    { when: "1-hafta", what: "Brif, sayt, ijtimoiy tarmoqlar va reklama kabinetlari auditi, kirish huquqlari" },
    { when: "2-hafta", what: "Strategiya, mediareja va kontent-reja — ko‘rsatamiz va kelishamiz" },
    { when: "Ishga tushirish", what: "Suratga olish, birinchi postlar, reklama kampaniyalari, arizalar CRM’ga" },
    { when: "Har hafta", what: "Reklamani optimallashtirish, arizalar va ularning narxi bo‘yicha hisobot" },
    { when: "Oyiga bir marta", what: "Kanallar bo‘yicha natijalar va keyingi oy rejasi" },
  ],
  faqTitle: "Reklama haqida savollar",
  faq: [
    { q: "Toshkentda Instagram’da reklama qancha turadi?", a: "SMM kalit topshirish — oyiga {smm}, Instagram va Facebook’da target — oyiga {target} va reklama byudjeti. Kanallaringiz uchun aniq summani shu sahifadagi kalkulyator ko‘rsatadi." },
    { q: "Nega faqat SEO bilan cheklanib bo‘lmaydi?", a: "SEO birinchi arizalarni 3–6 oydan keyin va faqat qidiruvdan beradi. Target va Telegram’dagi reklama birinchi haftadan murojaatlar olib keladi, SMM esa hali tanlayotganlarni isitadi. Birgalikda kanallar arzonroq ishlaydi: reklama sayt mehmonlarini qayta topadi, qidiruv esa brendni eslab qolganlarni ushlaydi." },
    { q: "Bepul sayt yaxshilashlariga nima kiradi?", a: "Agar sayt bizda yaratilgan va kamida 3 oylik marketing shartnomasi amal qilsa — xatolarni tuzatish, yuklanish tezligi, metateglar va belgilash, qidiruv so‘rovlari uchun sarlavhalar va matnlar, Google va Yandex uchun texnik tuzatishlar. Yangi bo‘limlar va funksiyalar — alohida smeta bo‘yicha." },
    { q: "Reklamadan QQSni kim to‘laydi?", a: "Reklama byudjetini siz to‘g‘ridan-to‘g‘ri reklama tizimlariga to‘laysiz — Yandex, Telegram va boshqalar unga 12% QQS qo‘shadi. Bizning komissiyamiz — byudjetdan 10%, studiya ishi — QQSsiz." },
    { q: "Bitta kanalni ulasa bo‘ladimi?", a: "Ha. Ko‘pincha Instagram’dagi target yoki Telegram’dagi reklamadan boshlashadi — ular birinchi haftadan arizalar beradi. Qolgan kanallar qaysi takliflar yaxshiroq sotishi aniq bo‘lganda ulanadi." },
    { q: "Shartnomaning eng kam muddati qancha?", a: "Uch oy: bundan kam muddatda reklama o‘rganib ulgurmaydi, SEO esa natija ko‘rsata olmaydi. Keyin — oyma-oy." },
  ],
  articlesTitle: "Marketing haqida maqolalar",
  articlesLead: "Mashhur keyslar va ko‘p uchraydigan xatolar haqida qisqa tahlillar — va ulardan O‘zbekistonda nimani qo‘llash mumkin. Yangi maqolalar har kuni chiqadi.",
  readMore: "O‘qish",
  sourceLabel: "Faktlar manbasi",
  tipsTitle: "O‘zingizda nima qilish kerak",
  articleCtaTitle: "Arizalar olib keladigan marketing kerakmi?",
  articleCtaText: "Kanallarni kalkulyatorda hisoblang yoki bizga yozing — ish kuni davomida javob beramiz.",
  articleCtaButton: "Kalkulyatorni ochish",
  allArticles: "Marketing haqidagi barcha maqolalar",
  homeKicker: "Marketing",
  homeTitle: "Sayt reklamasini hisoblang",
  homeLead: "SMM, target, kontekst, Telegram Ads va SEO — bitta jamoa. Saytni biz qilsak, tuzatishlar va SEO yaxshilashlar — bepul.",
  homeMore: "Marketing haqida hammasi",
  home: "Bosh sahifa",
};

const zh: MarketingCopy = {
  seoTitle: "塔什干企业营销推广：社媒运营、定向广告、搜索广告 — DevUz Studio",
  seoDescription:
    "由为您搭建网站的工作室提供社媒运营、Instagram 定向广告、Google 与 Yandex 搜索广告、Telegram 广告和 SEO。在线费用计算器。网站与营销都交给我们——网站修复与 SEO 优化免费。",
  kicker: "营销",
  title: "带来询盘而不只是曝光的营销",
  lead: "社媒运营、定向广告、Google 与 Yandex 搜索广告、Telegram 广告和 SEO，一个团队完成。所有渠道都指向我们熟悉到每个按钮的网站，每条线索都会带着渠道标记进入 CRM。",
  ctaCalc: "计算营销费用",
  ctaDiscuss: "洽谈推广",
  utp: {
    badge: "网站 + 营销",
    title: "我们建站并负责推广——网站修复与 SEO 优化免费",
    text: "只要您的网站由 DevUz 推广，我们免费修复网站问题并进行 SEO 优化：加载速度、元标签与结构化数据、针对搜索词的标题和文案、Google 与 Yandex 更新后的技术调整。",
    fine: "条件：网站由我们制作，且营销合同期不少于 3 个月。新栏目和新功能另行报价。",
  },
  whyTitle: "为什么由建站团队负责推广",
  why: [
    { title: "SEO 只是一个渠道，而且最慢", text: "搜索带来的首批询盘需要 3–6 个月，而购买决定往往更早在 Instagram 和 Telegram 上做出。" },
    { title: "所有渠道都指向我们了如指掌的网站", text: "像素、标签、转化目标和按钮事件当天由我们自己设置，无需给外部开发者写需求。" },
    { title: "每条线索都进入同一个 CRM 和 Telegram", text: "来自广告、Instagram、Telegram 广告和搜索的线索集中一处并标注渠道，清楚看到什么在带来销售。" },
    { title: "不存在“这不归我们管”", text: "广告指向的页面转化差，我们直接改页面，无需追究是谁的责任。" },
    { title: "一份合同、一位经理、一份报告", text: "每月一次：各渠道的询盘数、单条询盘成本和销售，集中在一页。" },
    { title: "比大型代理商更省", text: "同样的工作内容，费用比塔什干大型全案代理商的报价低 10%。" },
  ],
  calc: {
    kicker: "计算器",
    title: "营销费用计算器",
    lead: "选择渠道和广告预算，我们计算首月和每月费用。",
    channels: "渠道",
    context: "搜索广告",
    contextNone: "不投搜索广告",
    contextGoogle: "Google",
    contextBoth: "Google 与 Yandex",
    budget: "每月广告预算",
    budgetHint: "直接支付给广告平台。起步建议每个渠道 $500 起。",
    siteToo: "网站也由我们制作",
    siteTooHint: "网站修复与 SEO 优化免费",
    firstMonth: "首月",
    monthly: "每月服务费",
    adBudget: "广告预算",
    vat: "广告平台收取的 12% 增值税",
    commission: "预算的 10% 佣金",
    total: "含广告每月合计",
    prepay: "预付 3 个月，服务费减 5%",
    discuss: "在聊天中洽谈",
    sent: "报价已发到聊天中，我们会在那里回复",
    empty: "请至少选择一个渠道",
    prefill: "我需要营销：{channels}。每月广告预算 {budget}。计算结果：首月 {first}，之后每月服务费 {monthly}。",
    prefillSite: " 网站也由你们制作。",
  },
  servicesTitle: "服务与价格",
  servicesLead: "首月费用更高：包含策略、页面风格、媒体计划和广告账户设置。",
  monthlyCol: "每月",
  firstCol: "首月",
  from: "起",
  plusCommission: "+ 广告预算的 10%",
  projectsTitle: "一次性项目",
  perHour: "/ 小时",
  budgetBased: [
    "达人营销——活动预算的 20%，预算 $1,000 起。",
    "程序化展示广告——广告预算的 15%，预算 $1,000 起。",
    "公关推广——每月 7,200,000 苏姆起，另加投放预算的 20%。",
  ],
  vatNote: "广告预算单独支付：Yandex、Telegram 等广告平台会在其上加收 12% 增值税。工作室价格以苏姆计，不含增值税。",
  processTitle: "如何开始",
  process: [
    { when: "第 1 周", what: "需求简报，审计网站、社媒和广告账户，开通权限" },
    { when: "第 2 周", what: "策略、媒体计划和内容计划——展示并确认" },
    { when: "上线", what: "拍摄、首批内容、广告投放，线索进入 CRM" },
    { when: "每周", what: "优化广告，报告询盘数量和成本" },
    { when: "每月", what: "各渠道结果和下月计划" },
  ],
  faqTitle: "推广常见问题",
  faq: [
    { q: "在塔什干做 Instagram 推广要多少钱？", a: "全案社媒运营每月 {smm}，Instagram 与 Facebook 定向广告每月 {target}，另加广告预算。本页的计算器会按您的渠道给出准确金额。" },
    { q: "为什么不能只做 SEO？", a: "SEO 需要 3–6 个月才带来首批询盘，而且只来自搜索。定向广告和 Telegram 广告第一周就能带来咨询，社媒运营则持续影响仍在比较的客户。多渠道配合成本更低：广告追回网站访客，搜索承接记住品牌的人。" },
    { q: "免费的网站优化包括什么？", a: "若网站由我们制作且营销合同期不少于 3 个月：修复问题、加载速度、元标签与结构化数据、针对搜索词的标题和文案、面向 Google 与 Yandex 的技术调整。新栏目和新功能另行报价。" },
    { q: "广告的增值税由谁支付？", a: "广告预算由您直接支付给广告平台——Yandex、Telegram 等会加收 12% 增值税。我们的佣金为预算的 10%，工作室服务费不含增值税。" },
    { q: "可以只开通一个渠道吗？", a: "可以。多数客户从 Instagram 定向广告或 Telegram 广告开始——第一周就有询盘。确定哪些产品卖得最好后，再增加其他渠道。" },
    { q: "合同最短期限是多久？", a: "三个月：时间更短的话，广告来不及完成学习，SEO 也无法显现效果。之后按月续约。" },
  ],
  articlesTitle: "营销文章",
  articlesLead: "关于知名案例和常见错误的简短分析，以及哪些做法适用于乌兹别克斯坦。",
  readMore: "阅读",
  sourceLabel: "事实来源",
  tipsTitle: "可以马上做的事",
  articleCtaTitle: "需要能带来询盘的营销吗？",
  articleCtaText: "在计算器中估算渠道费用，或给我们留言——一个工作日内回复。",
  articleCtaButton: "打开计算器",
  allArticles: "全部营销文章",
  homeKicker: "营销",
  homeTitle: "估算网站推广费用",
  homeLead: "社媒运营、定向广告、搜索广告、Telegram 广告和 SEO，一个团队完成。网站由我们制作的话，修复与 SEO 优化免费。",
  homeMore: "了解营销服务",
  home: "首页",
};

const uk: MarketingCopy = {
  seoTitle: "Маркетинг і просування бізнесу в Ташкенті: SMM, таргет, контекст — DevUz Studio",
  seoDescription:
    "SMM, таргет в Instagram, контекстна реклама Google і Яндекс, Telegram Ads і SEO від студії, яка робить ваш сайт. Онлайн-калькулятор вартості. Сайт і маркетинг у нас — виправлення і SEO-доопрацювання безкоштовно.",
  kicker: "Маркетинг",
  title: "Маркетинг, який приводить заявки, а не лише охоплення",
  lead: "SMM, таргет, контекст у Google і Яндексі, Telegram Ads і SEO — однією командою. Усі канали ведуть на сайт, який ми знаємо до останньої кнопки, а кожна заявка потрапляє в CRM з позначкою каналу.",
  ctaCalc: "Розрахувати маркетинг",
  ctaDiscuss: "Обговорити просування",
  utp: {
    badge: "Сайт + маркетинг",
    title: "Робимо сайт і просуваємо його — виправлення і SEO-доопрацювання безкоштовно",
    text: "Поки ваш сайт на просуванні в DevUz, виправляємо помилки сайту і робимо SEO-доопрацювання без доплати: швидкість завантаження, метатеги і розмітка, заголовки й тексти під пошукові запити, технічні правки після оновлень Google і Яндекса.",
    fine: "Умова — сайт зроблено в нас і діє договір на маркетинг від 3 місяців. Нові розділи і функції рахуємо окремо.",
  },
  whyTitle: "Чому просуватися в тих, хто робив сайт",
  why: [
    { title: "SEO — лише один канал, і найповільніший", text: "Перші заявки з пошуку приходять через 3–6 місяців. А рішення про купівлю часто ухвалюють раніше — в Instagram і Telegram." },
    { title: "Усі канали ведуть на сайт, який ми знаємо зсередини", text: "Пікселі, теги, цілі й події на кнопках ставимо самі того ж дня, без ТЗ сторонньому розробнику." },
    { title: "Кожна заявка — в одну CRM і Telegram", text: "З реклами, Instagram, Telegram Ads і пошуку — в одне місце з позначкою каналу. Видно, що приносить продажі." },
    { title: "Жодного «це не до нас»", text: "Реклама веде на сторінку, яка погано продає, — виправляємо сторінку самі. Не треба з’ясовувати, хто винен." },
    { title: "Один договір, один менеджер, один звіт", text: "Раз на місяць — заявки, вартість заявки і продажі за кожним каналом на одній сторінці." },
    { title: "Дешевше за великі агенції", text: "Робота на 10% дешевша за прайс великих агенцій повного циклу Ташкента за того ж складу." },
  ],
  calc: {
    kicker: "Калькулятор",
    title: "Калькулятор маркетингу",
    lead: "Позначте канали і бюджет на рекламу — порахуємо перший місяць і щомісячну вартість.",
    channels: "Канали",
    context: "Контекстна реклама",
    contextNone: "Без контексту",
    contextGoogle: "Google",
    contextBoth: "Google і Яндекс",
    budget: "Рекламний бюджет на місяць",
    budgetHint: "Сплачується напряму в рекламні системи. На старт — від $500 на канал.",
    siteToo: "Сайт теж робимо ми",
    siteTooHint: "Виправлення і SEO-доопрацювання сайту — безкоштовно",
    firstMonth: "Перший місяць",
    monthly: "Робота на місяць",
    adBudget: "Рекламний бюджет",
    vat: "ПДВ 12% рекламних систем",
    commission: "Комісія 10% від бюджету",
    total: "Усього на місяць з рекламою",
    prepay: "При оплаті 3 місяців наперед — мінус 5% на роботу",
    discuss: "Обговорити в чаті",
    sent: "Розрахунок у чаті — відповімо там",
    empty: "Оберіть хоча б один канал",
    prefill: "Потрібен маркетинг: {channels}. Рекламний бюджет — {budget} на місяць. За калькулятором: перший місяць {first}, далі {monthly} на місяць за роботу.",
    prefillSite: " Сайт теж робите ви.",
  },
  servicesTitle: "Послуги і ціни",
  servicesLead: "Перший місяць дорожчий: у нього входять стратегія, фірмовий стиль сторінок, медіаплан і налаштування кабінетів.",
  monthlyCol: "На місяць",
  firstCol: "Перший місяць",
  from: "від",
  plusCommission: "+ 10% від рекламного бюджету",
  projectsTitle: "Разові проєкти",
  perHour: "/ година",
  budgetBased: [
    "Інфлюенс-маркетинг — 20% від бюджету кампанії, бюджет від $1 000.",
    "Медійна реклама (programmatic) — 15% від рекламного бюджету, бюджет від $1 000.",
    "PR-просування — від 7 200 000 сум на місяць плюс 20% від бюджету розміщень.",
  ],
  vatNote: "Рекламний бюджет сплачується окремо: Яндекс, Telegram та інші рекламні системи нараховують на нього ПДВ 12%. Ціни студії — в сумах, без ПДВ.",
  processTitle: "Як починаємо",
  process: [
    { when: "Тиждень 1", what: "Бриф, аудит сайту, соцмереж і рекламних кабінетів, доступи" },
    { when: "Тиждень 2", what: "Стратегія, медіаплан і контент-план — показуємо й погоджуємо" },
    { when: "Запуск", what: "Зйомки, перші публікації, рекламні кампанії, заявки в CRM" },
    { when: "Щотижня", what: "Оптимізація реклами, звіт про заявки та їхню вартість" },
    { when: "Раз на місяць", what: "Підсумки за каналами і план на наступний місяць" },
  ],
  faqTitle: "Питання про просування",
  faq: [
    { q: "Скільки коштує просування в Instagram у Ташкенті?", a: "SMM під ключ — {smm} на місяць, таргет в Instagram і Facebook — {target} на місяць плюс рекламний бюджет. Точну суму під ваші канали покаже калькулятор на цій сторінці." },
    { q: "Чому не можна обмежитися SEO?", a: "SEO дає перші заявки через 3–6 місяців і лише з пошуку. Таргет і реклама в Telegram приносять звернення з першого тижня, а SMM прогріває тих, хто поки обирає. Разом канали працюють дешевше: реклама наздоганяє відвідувачів сайту, а пошук підхоплює тих, хто запам’ятав бренд." },
    { q: "Що входить у безкоштовні доопрацювання сайту?", a: "Якщо сайт зроблено в нас і діє договір на маркетинг від 3 місяців — виправлення помилок, швидкість завантаження, метатеги і розмітка, заголовки й тексти під пошукові запити, технічні правки для Google і Яндекса. Нові розділи і функції — за окремим кошторисом." },
    { q: "Хто сплачує ПДВ з реклами?", a: "Рекламний бюджет ви сплачуєте напряму в рекламні системи — Яндекс, Telegram та інші нараховують на нього ПДВ 12%. Наша комісія — 10% від бюджету, робота студії — без ПДВ." },
    { q: "Чи можна підключити один канал?", a: "Так. Найчастіше починають з таргету в Instagram або реклами в Telegram — вони дають заявки з першого тижня. Інші канали підключаються, коли зрозуміло, які пропозиції продають краще." },
    { q: "Який мінімальний строк договору?", a: "Три місяці: за коротший строк реклама не встигає навчитися, а SEO — показати результат. Далі — помісячно." },
  ],
  articlesTitle: "Статті про маркетинг",
  articlesLead: "Короткі розбори відомих кейсів і частих помилок — і що з цього застосувати в Узбекистані.",
  readMore: "Читати",
  sourceLabel: "Джерело фактів",
  tipsTitle: "Що зробити у себе",
  articleCtaTitle: "Потрібен маркетинг, який приводить заявки?",
  articleCtaText: "Порахуйте канали в калькуляторі або напишіть нам — відповімо протягом робочого дня.",
  articleCtaButton: "Відкрити калькулятор",
  allArticles: "Усі статті про маркетинг",
  homeKicker: "Маркетинг",
  homeTitle: "Порахуйте просування сайту",
  homeLead: "SMM, таргет, контекст, Telegram Ads і SEO — однією командою. Якщо сайт робимо ми, виправлення і SEO-доопрацювання — безкоштовно.",
  homeMore: "Усе про маркетинг",
  home: "Головна",
};

const pl: MarketingCopy = {
  seoTitle: "Marketing i promocja firmy w Taszkencie: social media, reklama, Google i Yandex — DevUz Studio",
  seoDescription:
    "Social media, reklama na Instagramie, reklama w Google i Yandex, Telegram Ads i SEO od studia, które robi Twoją stronę. Kalkulator kosztów online. Strona i marketing u nas — poprawki i usprawnienia SEO za darmo.",
  kicker: "Marketing",
  title: "Marketing, który przynosi zapytania, a nie tylko zasięgi",
  lead: "Social media, reklama płatna, Google i Yandex, Telegram Ads i SEO — jeden zespół. Każdy kanał prowadzi na stronę, którą znamy do ostatniego przycisku, a każde zapytanie trafia do CRM z oznaczeniem kanału.",
  ctaCalc: "Policz marketing",
  ctaDiscuss: "Porozmawiajmy o promocji",
  utp: {
    badge: "Strona + marketing",
    title: "Robimy stronę i ją promujemy — poprawki i usprawnienia SEO za darmo",
    text: "Dopóki Twoja strona jest promowana przez DevUz, poprawiamy jej błędy i wprowadzamy usprawnienia SEO bez dopłat: szybkość ładowania, meta tagi i dane strukturalne, nagłówki i teksty pod frazy wyszukiwania, poprawki techniczne po aktualizacjach Google i Yandex.",
    fine: "Warunek — strona została zrobiona u nas i obowiązuje umowa marketingowa na co najmniej 3 miesiące. Nowe sekcje i funkcje wyceniamy osobno.",
  },
  whyTitle: "Dlaczego promocja u tych, którzy zrobili stronę",
  why: [
    { title: "SEO to tylko jeden kanał, i to najwolniejszy", text: "Pierwsze zapytania z wyszukiwarki pojawiają się po 3–6 miesiącach, a decyzje zakupowe zapadają często wcześniej — na Instagramie i Telegramie." },
    { title: "Każdy kanał prowadzi na stronę, którą znamy od środka", text: "Piksele, tagi, cele i zdarzenia na przyciskach ustawiamy sami tego samego dnia, bez zlecenia dla zewnętrznego programisty." },
    { title: "Każde zapytanie trafia do jednego CRM i Telegrama", text: "Z reklam, Instagrama, Telegram Ads i wyszukiwarki — w jedno miejsce, z oznaczeniem kanału. Widać, co naprawdę sprzedaje." },
    { title: "Żadnego „to nie do nas”", text: "Jeśli reklama prowadzi na stronę, która słabo sprzedaje, poprawiamy stronę sami. Nie trzeba szukać winnego." },
    { title: "Jedna umowa, jeden opiekun, jeden raport", text: "Raz w miesiącu: zapytania, koszt zapytania i sprzedaż z każdego kanału na jednej stronie." },
    { title: "Taniej niż duże agencje", text: "Praca jest o 10% tańsza od cennika dużych agencji full-service w Taszkencie, przy tym samym zakresie." },
  ],
  calc: {
    kicker: "Kalkulator",
    title: "Kalkulator marketingu",
    lead: "Zaznacz kanały i budżet reklamowy — policzymy pierwszy miesiąc i koszt miesięczny.",
    channels: "Kanały",
    context: "Reklama w wyszukiwarce",
    contextNone: "Bez reklamy w wyszukiwarce",
    contextGoogle: "Google",
    contextBoth: "Google i Yandex",
    budget: "Miesięczny budżet reklamowy",
    budgetHint: "Płatny bezpośrednio do systemów reklamowych. Na start — od $500 na kanał.",
    siteToo: "Stronę też robimy my",
    siteTooHint: "Poprawki i usprawnienia SEO strony — za darmo",
    firstMonth: "Pierwszy miesiąc",
    monthly: "Praca miesięcznie",
    adBudget: "Budżet reklamowy",
    vat: "VAT 12% systemów reklamowych",
    commission: "Prowizja 10% od budżetu",
    total: "Razem miesięcznie z reklamą",
    prepay: "Przy płatności za 3 miesiące z góry — 5% mniej za pracę",
    discuss: "Omów na czacie",
    sent: "Wycena jest na czacie — tam odpowiemy",
    empty: "Wybierz co najmniej jeden kanał",
    prefill: "Potrzebuję marketingu: {channels}. Budżet reklamowy — {budget} miesięcznie. Według kalkulatora: pierwszy miesiąc {first}, potem {monthly} miesięcznie za pracę.",
    prefillSite: " Stronę też robicie wy.",
  },
  servicesTitle: "Usługi i ceny",
  servicesLead: "Pierwszy miesiąc kosztuje więcej: obejmuje strategię, styl stron, media plan i konfigurację kont reklamowych.",
  monthlyCol: "Miesięcznie",
  firstCol: "Pierwszy miesiąc",
  from: "od",
  plusCommission: "+ 10% budżetu reklamowego",
  projectsTitle: "Projekty jednorazowe",
  perHour: "/ godz.",
  budgetBased: [
    "Influencer marketing — 20% budżetu kampanii, budżet od $1 000.",
    "Reklama programmatic — 15% budżetu reklamowego, budżet od $1 000.",
    "PR — od 7 200 000 UZS miesięcznie plus 20% budżetu publikacji.",
  ],
  vatNote: "Budżet reklamowy płaci się osobno: Yandex, Telegram i inne systemy reklamowe doliczają do niego VAT 12%. Ceny studia są w sumach, bez VAT.",
  processTitle: "Jak zaczynamy",
  process: [
    { when: "Tydzień 1", what: "Brief, audyt strony, social mediów i kont reklamowych, dostępy" },
    { when: "Tydzień 2", what: "Strategia, media plan i plan treści — pokazujemy i uzgadniamy" },
    { when: "Start", what: "Sesje, pierwsze publikacje, kampanie reklamowe, zapytania w CRM" },
    { when: "Co tydzień", what: "Optymalizacja reklam, raport o zapytaniach i ich koszcie" },
    { when: "Co miesiąc", what: "Wyniki według kanałów i plan na kolejny miesiąc" },
  ],
  faqTitle: "Pytania o promocję",
  faq: [
    { q: "Ile kosztuje promocja na Instagramie w Taszkencie?", a: "Kompleksowe prowadzenie social mediów to {smm} miesięcznie, reklama na Instagramie i Facebooku — {target} miesięcznie plus budżet reklamowy. Dokładną kwotę dla Twoich kanałów pokaże kalkulator na tej stronie." },
    { q: "Dlaczego nie wystarczy samo SEO?", a: "SEO daje pierwsze zapytania po 3–6 miesiącach i tylko z wyszukiwarki. Reklama w social mediach i na Telegramie przynosi zapytania od pierwszego tygodnia, a prowadzenie profili ogrzewa tych, którzy jeszcze wybierają. Razem kanały kosztują mniej: reklama dociera ponownie do odwiedzających stronę, a wyszukiwarka łapie tych, którzy zapamiętali markę." },
    { q: "Co obejmują darmowe usprawnienia strony?", a: "Jeśli stronę zrobiliśmy my i obowiązuje umowa marketingowa na co najmniej 3 miesiące: poprawki błędów, szybkość ładowania, meta tagi i dane strukturalne, nagłówki i teksty pod frazy, poprawki techniczne dla Google i Yandex. Nowe sekcje i funkcje — według osobnej wyceny." },
    { q: "Kto płaci VAT od reklamy?", a: "Budżet reklamowy płacisz bezpośrednio do systemów reklamowych — Yandex, Telegram i inne doliczają do niego VAT 12%. Nasza prowizja to 10% budżetu, praca studia jest bez VAT." },
    { q: "Czy można zacząć od jednego kanału?", a: "Tak. Najczęściej zaczyna się od reklamy na Instagramie albo na Telegramie — dają zapytania od pierwszego tygodnia. Kolejne kanały dochodzą, gdy widać, które oferty sprzedają najlepiej." },
    { q: "Jaki jest minimalny okres umowy?", a: "Trzy miesiące: w krótszym czasie reklama nie zdąży się nauczyć, a SEO pokazać efektów. Potem — z miesiąca na miesiąc." },
  ],
  articlesTitle: "Artykuły o marketingu",
  articlesLead: "Krótkie omówienia znanych kampanii i częstych błędów — i co z tego zastosować w Uzbekistanie.",
  readMore: "Czytaj",
  sourceLabel: "Źródło faktów",
  tipsTitle: "Co zrobić u siebie",
  articleCtaTitle: "Potrzebujesz marketingu, który przynosi zapytania?",
  articleCtaText: "Policz kanały w kalkulatorze albo napisz do nas — odpowiemy w ciągu dnia roboczego.",
  articleCtaButton: "Otwórz kalkulator",
  allArticles: "Wszystkie artykuły o marketingu",
  homeKicker: "Marketing",
  homeTitle: "Policz promocję strony",
  homeLead: "Social media, reklama płatna, wyszukiwarki, Telegram Ads i SEO — jeden zespół. Jeśli stronę robimy my, poprawki i usprawnienia SEO są za darmo.",
  homeMore: "Wszystko o marketingu",
  home: "Strona główna",
};

export const marketingCopy: Record<Locale, MarketingCopy> = { ru, en, uz, zh, uk, pl };

/** Путь раздела без языка: `/{locale}/marketing`. */
export const MARKETING_PATH = "marketing";
